app:
    resource: "@AppBundle/Controller/"
    type:     annotation

easy_admin_bundle:
    resource: "@AppBundle/Controller/Admin/AdminController.php"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

JMSTranslationBundle_ui:
    resource: "@JMSTranslationBundle/Controller/"
    type: annotation
    prefix: /admin/_trans

artgris_bundle_file_manager:
    resource: "@ArtgrisFileManagerBundle/Controller"
    type:     annotation
    prefix: /admin/tools/manager

artgris_media:
    resource: "@ArtgrisMediaBundle/Resources/config/routing.yml"

block:
   resource: "@ArkounayBlockI18nBundle/Resources/config/routing.yml"